repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: \.svn/
      - id: end-of-file-fixer
        exclude: \.svn/
      - id: check-yaml
      - id: check-xml
        exclude: \.svn/
      - id: check-added-large-files
        args: ['--maxkb=1024']
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-case-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']
        exclude: \.svn/
      - id: check-symlinks
